"""set owner_id ondelete set null

Revision ID: 15a95cb48ce6
Revises: 666ca9cd8fb1
Create Date: 2025-04-01 14:17:32.630901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a95cb48ce6'
down_revision: Union[str, None] = '666ca9cd8fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_owner_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_owner_id_fkey', 'clients', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
